% -------------------------------------------------------------------
%  Generated by MATLAB on 6-May-2024 13:49:21
%  MATLAB version: 23.2.0.2515942 (R2023b) Update 7
% -------------------------------------------------------------------
                                         

Omega = ...
  [0 1.6616634036414772;
   1.0E+7 1.6616634036414772];

Omega_float = 1.6616634036414772;

T = 5929.4726693630819;

a_float = 7080.6;

e_float = 9.79E-5;

eccentricity = ...
  [0 9.79E-5;
   1.0E+7 9.79E-5];

i_float = 1.7139133254584316;

inclination = ...
  [0 1.7139133254584316;
   1.0E+7 1.7139133254584316];

mean_motion = ...
  [0 0.0010596533043560682;
   1.0E+7 0.0010596533043560682];

mu = ...
  [0 398600.4418;
   1.0E+7 398600.4418];

mu_float = 398600.4418;

n_float = 0.0010596533043560682;

nu_float = 0;

omega = ...
  [0 2.1027709374735162;
   1.0E+7 2.1027709374735162];

omega_float = 2.1027709374735162;

orbitType = 'num';
orbitType = convertCharsToStrings(orbitType);

semimajorAxis = ...
  [0 7080.6;
   1.0E+7 7080.6];

trueAnomaly = ...
  [0 0;
   1.0E+7 0];

rE = 6371; %km
altitudeFloat = a_float - rE; %km

altitude = ...
  [0 altitudeFloat;
   1.0E+7 altitudeFloat];

%% Sun Elements
Sun_Omega_float = deg2rad(348.74);

Sun_Omega = ...
  [0 Sun_Omega_float;
   1.0E+7 Sun_Omega_float];

Sun_T = 365.256*24*3600;

Sun_a_float = 149.6e6;

Sun_e_float = 0.0167086;

Sun_eccentricity = ...
  [0 Sun_e_float;
   1.0E+7 Sun_e_float];

Sun_i_float = deg2rad(23.44);

Sun_inclination = ...
  [0 Sun_i_float;
   1.0E+7 Sun_i_float];

Sun_n_float = 2*pi / Sun_T; % Mean motion in rad/s

Sun_mean_motion = ...
  [0 Sun_n_float;
   1.0E+7 Sun_n_float];

Sun_mu_float = 1.327124e11;

Sun_mu = ...
  [0 Sun_mu_float;
   1.0E+7 Sun_mu_float];

Sun_omega_float = deg2rad(102.93);

Sun_omega = ...
  [0 Sun_omega_float;
   1.0E+7 Sun_omega_float];

Sun_semimajorAxis = ...
  [0 Sun_a_float;
   1.0E+7 Sun_a_float];

Sun_trueAnomaly = ...
  [0 0;
   1.0E+7 0];





