% -------------------------------------------------------------------
%  Generated by MATLAB on 6-May-2024 01:20:54
%  MATLAB version: 23.2.0.2515942 (R2023b) Update 7
% -------------------------------------------------------------------
                                         

orbitType = 'num';
orbitType = convertCharsToStrings(orbitType);

